### ISSUE TITLE
Need to fix build to work with gcc4

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/ArmyKnife#2]
Creator: Scott McCreary
URL: http://dev.osdrawer.net/issues/273

The Makefiles and perhaps some other tweaks made be needed to get Army Knife building on a gcc4 Haiku.

**Comment by scottmc** [comment]
Is this still the case?  Thought this one got fixed.

**Comment by scottmc** [comment]
Can close?

**Comment by diversys** [comment]
Yep. Fixed in f31ef34.
