### ISSUE TITLE
Confusing apply button

### ISSUE THREAD

**Issue by hometue** [HaikuArchives/ArmyKnife#20]
The apply button in the UI is very confusing as it also breaks the normal convention that when modifying a file you save the file afterwards, so perhaps changing it to save would be a better idea.
![screenshot8](https://f.cloud.github.com/assets/1729510/1652851/16712a36-5b23-11e3-8cb4-5e28e26bb76f.png)

**Comment by bach5000** [comment]
I'll do this one :)
