### ISSUE TITLE
Chinese Characters?

### ISSUE THREAD

**Issue by hometue** [HaikuArchives/ArmyKnife#21]
Armyknife seems to be unable to read Chinese characters as it shows a blank where the field with Chinese character is.
![screenshot4](https://f.cloud.github.com/assets/1729510/1652567/cc06cae6-5b18-11e3-9956-29cf3c5081f9.png)
![screenshot5](https://f.cloud.github.com/assets/1729510/1652568/cc101704-5b18-11e3-9be5-288cecd5d089.png)

**Comment by scottmc** [comment]
@hometue can you recheck this and let us know if it is still an issue in newer Haiku nightly builds?

**Comment by Oyami-Srk** [comment]
Issue has been solved on newer nightly builds.
![img](https://s1.ax1x.com/2018/01/09/pKTQCn.jpg)

**Comment by scottmc** [comment]
Thanks for checking.
