### ISSUE TITLE
No Help menu

### ISSUE THREAD

**Issue by hometue** [HaikuArchives/ArmyKnife#22]
There seems to be no help menu for ArmyKnife. For an app that has menu not self-explanatory it may seem better to explain what they do.
![screenshot8](https://f.cloud.github.com/assets/1729510/1652856/274106ce-5b23-11e3-8026-0686273ec9ef.png)

**Comment by humdingerb** [comment]
Doesn't work with the merged #38 .

**Comment by bach5000** [comment]
I noticed this was closed and merged ... but reopened?
@humdingerb could I try to fix the problem(s)?

**Comment by humdingerb** [comment]
Yes, please. As said, have a look at Filer's main.cpp.

**Comment by bach5000** [comment]
@humdingerb Oh... I finally understand (or that's what I think)
In `Filer` there are `GetParent` and `GetRef` functions. You want me to use these to determine the relative path of the docs, right?

**Comment by scottmc** [comment]
that sounds right.  Keep in mind that an .hpkg can be put in system/packages or home/config/packages, so it needs to be able to figure out which location it gets put in.
