### ISSUE TITLE
Tags not saved.

### ISSUE THREAD

**Issue by hometue** [HaikuArchives/ArmyKnife#23]
The tags are not saved after being edited. To show it the files are transferred to my Win7 system and the media info being displayed in VLC where it should show the edited tags.
![screenshot1](https://f.cloud.github.com/assets/1729510/1652780/540dbb86-5b21-11e3-8e52-7883d7098c01.png)
![screenshot2](https://f.cloud.github.com/assets/1729510/1652781/540e22d8-5b21-11e3-9206-464868142ebf.png)
![screenshot3](https://f.cloud.github.com/assets/1729510/1652782/54123a58-5b21-11e3-9a52-58571897e73a.png)

**Comment by humdingerb** [comment]
From the first screenshot, it might be a user error. Only the "Attributes" radio button is active. ID3 tags were never written. Should've marked the "Also apply to tags" checkbox.

That said, I found that esp. if you're applying to a number of files, all the files are only written after the second click on "Apply". Always keep a Tracker window showing the modified date open...

**Comment by scottmc** [comment]
Maybe a "status" bar could be added at the bottom to show things such as when there are pending changes or changes have been applied, etc...

**Comment by scottmc** [comment]
Marking this as closed, as it is reported to be working ok now.
