### ISSUE TITLE
v5.1.0 doesn't compile

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArmyKnife#33]
Doesn't compile, though the taglib and musicbrainz devel packages are installed:

`In file included from /Source-Ports/ArmyKnife/source/albumpictureview.h:7,
                 from /Source-Ports/ArmyKnife/source/albumpictureview.cpp:1:
/boot/system/develop/headers/taglib/id3v2tag.h:29: tag.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:30: tbytevector.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:31: tstring.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:32: tlist.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:33: tmap.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:34: taglib_export.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2tag.h:36: id3v2framefactory.h: No such file or directory
In file included from /Source-Ports/ArmyKnife/source/albumpictureview.h:8,
                 from /Source-Ports/ArmyKnife/source/albumpictureview.cpp:1:
/boot/system/develop/headers/taglib/mpegfile.h:29: taglib_export.h: No such file or directory
/boot/system/develop/headers/taglib/mpegfile.h:30: tfile.h: No such file or directory
/boot/system/develop/headers/taglib/mpegfile.h:32: mpegproperties.h: No such file or directory
In file included from /Source-Ports/ArmyKnife/source/albumpictureview.h:9,
                 from /Source-Ports/ArmyKnife/source/albumpictureview.cpp:1:
/boot/system/develop/headers/taglib/id3v2frame.h:29: tstring.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2frame.h:30: tbytevector.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2frame.h:31: taglib_export.h: No such file or directory
In file included from /Source-Ports/ArmyKnife/source/albumpictureview.h:10,
                 from /Source-Ports/ArmyKnife/source/albumpictureview.cpp:1:
/boot/system/develop/headers/taglib/id3v2header.h:29: tbytevector.h: No such file or directory
/boot/system/develop/headers/taglib/id3v2header.h:30: taglib_export.h: No such file or directory
In file included from /Source-Ports/ArmyKnife/source/albumpictureview.h:11,
                 from /Source-Ports/ArmyKnife/source/albumpictureview.cpp:1:
/boot/system/develop/headers/taglib/attachedpictureframe.h:29: id3v2frame.h: No such file or directory
/boot/system/develop/headers/taglib/attachedpictureframe.h:30: id3v2header.h: No such file or directory
/boot/system/develop/headers/taglib/attachedpictureframe.h:31: taglib_export.h: No such file or directory
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86-gcc2-release/albumpictureview.o' failed
`

**Comment by scottmc** [comment]
perhaps this is due to a gcc2 vs gcc4/5 issue?  IIRC newer versions of taglig no longer support gcc2.

**Comment by humdingerb** [comment]
Works now after the recent commits. Needs musicbrainz and taglib devel packages.
There's still a taglib 1.7.2-2 for gcc2 in HaikuDepot, took that and it worked.

**Comment by scottmc** [comment]
Nice!
