### ISSUE TITLE
The split pane should be resizable

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/ArmyKnife#5]
Creator: B. Humdinger
URL: http://dev.osdrawer.net/issues/277

The split pane between control view and list view should be resizable.

**Comment by scottmc** [comment]
Issue #1 should be solved before working on this one.

**Comment by scottmc** [comment]
See also issue #32.  Adding support for more tags, etc will require the panes to be resize-able and/or scrollable.
