### ISSUE TITLE
Still not working/open with 64bit nightly 55585

### ISSUE THREAD

**Issue by Brunobasta** [HaikuArchives/ArmyKnife#62]
http://0x0.st/-dni.png
http://0x0.st/-dni.png

**Comment by scottmc** [comment]
Recipe should be updated on haikuports, be sure to update the copyright section to put authors in the order listed in the CREDITS file, (you can leave out the Flip Side software part on the first line).  Once the recipe is written this issue can be closed.

**Comment by humdingerb** [comment]
I'm not sure having the all contributers of the CREDITS in the package copyright is sensible. Only the first 2 or 3 lines are visible in HaikuDepot. All contributers are still in the repo (and could be added to the AboutWindow).

I'd have a recipe ready to go with:

COPYRIGHT="2000-2001 Jason Burgess
	2008 Jonas Sundström, Ryan Leavengood
	2009-2021 HaikuArchives team"

**Comment by scottmc** [comment]
> 
> 
> I'm not sure having the all contributers of the CREDITS in the package copyright is sensible. Only the first 2 or 3 lines are visible in HaikuDepot. All contributers are still in the repo (and could be added to the AboutWindow).
> 
> I'd have a recipe ready to go with:
> 
> COPYRIGHT="2000-2001 Jason Burgess 2008 Jonas Sundström, Ryan Leavengood 2009-2021 HaikuArchives team"

Agreed.

**Comment by humdingerb** [comment]
Updated recipe for v5.1.1 deployed. Closing ticket.
