### ISSUE TITLE
Make a 5.1.2 release

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ArmyKnife#75]
Pull in any updated translations and make a fresh release of the current code.  Be sure to update version info in the program.

**Comment by humdingerb** [comment]
The catkeys are outdated and need to be re-generated and uploaded and translated at Polglot.
I also found a few strings that aren't yet translatable. Should I fix these things?
Also, the About text is quite elaborate compared with what's usually in there... Change it or keep it?

**Comment by scottmc** [comment]
> The catkeys are outdated and need to be re-generated and uploaded and translated at Polglot. I also found a few strings that aren't yet translatable. Should I fix these things? 
Yes, that'd be awesome

Also, the About text is quite elaborate compared with what's usually in there... Change it or keep it?
Simplification would be fine.

**Comment by humdingerb** [comment]
Created #76

**Comment by humdingerb** [comment]
Shall I prepare a new release now?
Including Spanish translation (94%). Also Japanese at 88%?

**Comment by scottmc** [comment]
yes, please do.
